# 日志管理工具配置文件

# 服务器配置
server:
  port: 6003
  host: "0.0.0.0"

# 认证配置
auth:
  username: "milk"
  password: "milk@2025"

# 日志文件配置
logs:
  # 日志文件目录路径（支持数组，可配置多个目录）
  directories:
    - "./logs"
  # 兼容旧版本，单个目录配置（如果设置了directories，此配置将被忽略）
  # directory: "./logs"
  # 确定的日志文件路径列表（支持相对路径和绝对路径，会显示在文件列表最前边）
  fixed_files:
    - "./logs/data.log"
    # 支持绝对路径示例（取消注释并修改为实际路径）
    # - "/var/log/nginx/access.log"
    # - "/var/log/nginx/error.log"
    # - "/var/log/mysql/mysql.log"
  # 日志文件名正则匹配模式，支持日期等变量
  pattern: ".*\\.log$"
  # 默认显示日志条数
  default_lines: 200
  # 最大搜索返回条数
  max_search_results: 1000
